on: push
name: Jenkins single-shot master
jobs:
  jenkinsfile-runner-prepackaged:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: jenkinsfile-runner-prepackaged
        uses: jenkinsci/jenkinsfile-runner-github-actions/jenkinsfile-runner-prepackaged@master
        with:
          pluginsTxt: plugins.txt
          jenkinsFile: Jenkinsfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
